if: branch != deploy

language: rust
rust: nightly
node_js: "node"

cache:
  cargo: true
  directories:
    - pkg
    - node_modules

jobs:
  include:
    - stage: Test rust
      script:
        - make test-rust
    - stage: Deploy rust
      if: branch = main
      script:
        - make deploy-wasm
    - stage: Test js
      script:
        - make test-js

notifications:
  email: false
