language: rust
rust: nightly
node_js:
  - "10" # <- not working, duplicated as `nvm install 10` below

cache:
  cargo: true
  directories:
    - node_modules
    - pkg
    - dist

jobs:
  include:
    - stage: Compile
      branches:
        except:
        - deploy
      script:
        - ls pkg/package.json || make build-wasm # build wasm if not cached
        - ls dist/index.html || make build-js-prod # build js if not cached
    # rust tests
    - stage: Test
      branches:
        except:
        - deploy
      script:
        - make test-rust
    # js tests
    - stage: Test
      branches:
        except:
        - deploy
      sudo: required # <- for the chrome install
      addons:
        chrome: stable
      install:
        - ls pkg/package.json || make build-wasm # build wasm if not cached
        - nvm install 10
        - nvm use 10
        - node --version
        - npm --version
        - npm ci
        - npx webdriver-manager update
      script:
        - make test-js
    # the `main` branch deploys to branch `deploy`
    - stage: Deploy
      branches:
        only:
        - main
      script:
        - make deploy-compiled-files

notifications:
  email: false
