if: branch != deploy
cache:
  - cargo
  - node_modules

jobs:
  include:
    - stage: TestRust
      language: rust
      rust: nightly
      before_install:
        - make rust-target
      script:
        - cargo check
        - cargo test -- --color always
    - stage: DeployRust
      if: branch = main
      language: rust
      rust: nightly
      before_install:
        - make rust-target
      script: bash bin/deploy-wasm-pack.sh
    - stage: TestJS
      language: node_js
      node_js: "node"
      before_script:
        - make rust-build

notifications:
  email: false
