language: rust
rust:
  - nightly
node_js:
  - "node"
cache:
  - cargo
  - node_modules

before_install:
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - ./bin/pre_compile
install:
  - cargo build

script:
  - cargo check
  - cargo test
  - make js-test

deploy:
  skip-cleanup: true
  provider: script
  script: bin/build-wasm-pack.sh
  on:
    branch: main

notifications:
  email: false
