language: rust
rust: nightly

cache:
  - cargo
  - node_modules
before_install:
  - rustup target add wasm32-unknown-unknown --toolchain nightly

jobs:
  include:
    - stage: test
      script:
        - cargo check
        - cargo test -- --color always
    - stage: test
      node_js: "node"
      before_script:
        - make rust-build
    - stage: deploy
      if: branch = main
      script: bash bin/build-wasm-pack.sh

notifications:
  email: false
