if: branch != deploy

language: rust
rust: nightly
node_js:
  - "10.4"

cache:
  cargo: true
  directories:
    - pkg
    - node_modules

jobs:
  include:
    - stage: Test rust
      script:
        - make test-rust
    - stage: Deploy wasm
      if: branch = main
      script:
        - make deploy-wasm
    - stage: Test js
      addons:
        apt:
          sources:
          - google-chrome
          packages:
          - google-chrome-stable
      before_script:
        - npx webdriver-manager update
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - make test-js

notifications:
  email: false
