if: branch != deploy
cache:
  - cargo
  directories:
    - pkg
    - node_modules

jobs:
  include:
    - stage: Test Rust
      language: rust
      rust: nightly
      script:
        - cargo check
        - cargo test -- --color always
    - stage: Deploy Rust
      if: branch = main
      language: rust
      rust: nightly
      script:
        - bash bin/deploy-wasm-pack.sh
    - stage: Test JS
      language: node_js
      node_js: "node"
      before_script:
        - make rust-build

notifications:
  email: false
