if: branch != deploy

language: rust
rust: nightly

cache:
  - cargo
  - node_modules
before_install:
  - rustup target add wasm32-unknown-unknown --toolchain nightly

jobs:
  include:
    - stage: test-rust
      script:
        - cargo check
        - cargo test -- --color always
    - stage: deploy-rust
      if: branch = main
      script: bash bin/deploy-wasm-pack.sh
    - stage: test-js
      node_js: "node"
      before_script:
        - make rust-build

notifications:
  email: false
