language: rust
rust: nightly

cache:
  - cargo
  - node_modules
before_install:
  - rustup target add wasm32-unknown-unknown --toolchain nightly

matrix:

  include:
  - script:
    - cargo check
    - cargo test -- --color always

  - node_js: "node"
    before_script:
      - make rust-build

deploy:
  skip-cleanup: true
  provider: script
  script: bash bin/build-wasm-pack.sh
  on:
    branch: main
notifications:
  email: false
