[package]
name = "galaxy_gen"
version = "0.1.0"
authors = ["Lynn Cyrin <firemagelynn@gmail.com>"]

[lib]
crate-type = ["cdylib"]
path = "src/rust/lib.rs"

[dependencies]
wasm-bindgen = "^0.2"
wasm-bindgen-cli = "^0.2"

[dev-dependencies]
cargo-watch = "^6"

[profile.release]
debug = true
